spring:
  application:
    name: svc-provider

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/svc_provider_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true

# Server Configuration
server:
  port: 8083

# Logging Configuration
logging:
  level:
    doodle.qa.com.svcproviderqa: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
