package doodle.qa.api.regression.config.Requests;

import lombok.Builder;
import lombok.Value;
import net.datafaker.Faker;

import java.util.UUID;

/**
 * A DTO for the calendar request body.
 * This class is immutable and uses the Builder pattern for easy object creation
 * with default values for all fields.
 */
@Value
@Builder
public class CalendarRequestBody {

    // A static Faker instance for generating default values.
    private static final Faker faker = new Faker();

    // The 'id' field has a default value generated by UUID.
    @Builder.Default
    String id = UUID.randomUUID().toString();

    // The 'name' field has a default value generated by Faker.
    @Builder.Default
    String name = faker.company().name() + " Calendar";

    // The 'description' field has a default value.
    @Builder.Default
    String description = "Description of Calendar";
}
